#ifndef CM_TESTS_CONFIGURATION_H_
#define CM_TESTS_CONFIGURATION_H_

/* Base */
#define RUN_BASE_TESTS 1
#define RUN_CM_OPERATIONS_TESTS 1
/* Base/Helpers */
#define RUN_HELPERS_TESTS 1
#define RUN_CM_NUMERIC_TESTS 1
#define RUN_CM_TEXT_TESTS 1
#define RUN_CM_GENERIC_TESTS 1
/* Collections */
#define RUN_COLLECTIONS_TESTS 1
#define RUN_CM_ARRAY_TESTS 1
#define RUN_CM_LIST_TESTS 1
#define RUN_CM_ARRAY_SET_TESTS 1
#define RUN_CM_SORTING_TESTS 1
#define RUN_CM_SEARCHING_TESTS 1
/* Cryptography */
#define RUN_CRYPTOGRAPHY 1
#define RUN_CM_CLASSICAL_CIPHERS 1
/* Media */
#define RUN_CM_COLORSPACE 1
#define RUN_CM_G711 1

#endif /* CM_TESTS_CONFIGURATION_H_ */
